package me.daoke.roadrank.dto;

import java.io.Serializable;

import me.daoke.roadrank.utils.JsonUtil;
import net.sf.json.JSONObject;

public class LoginConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginconfig.id
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginconfig.appKey
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginconfig.base
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    private String base;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginconfig.roadRank
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    private String roadRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginconfig.sicong
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    private String sicong;

 

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loginconfig
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginconfig.id
     *
     * @return the value of loginconfig.id
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginconfig.id
     *
     * @param id the value for loginconfig.id
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginconfig.appKey
     *
     * @return the value of loginconfig.appKey
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginconfig.appKey
     *
     * @param appKey the value for loginconfig.appKey
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }


    public JSONObject getBase() {
		return JsonUtil.nonDefaultMapper().fromJson(base, JSONObject.class);
	}
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginconfig.base
     *
     * @param base the value for loginconfig.base
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public void setBase(String base) {
        this.base = base == null ? null : base.trim();
    }

  
    public JSONObject getRoadRank() {
    	return JsonUtil.nonDefaultMapper().fromJson(roadRank, JSONObject.class);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginconfig.roadRank
     *
     * @param roadRank the value for loginconfig.roadRank
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public void setRoadRank(String roadRank) {
        this.roadRank = roadRank == null ? null : roadRank.trim();
    }

 
    public JSONObject getSicong() {
        return JsonUtil.nonDefaultMapper().fromJson(sicong, JSONObject.class);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginconfig.sicong
     *
     * @param sicong the value for loginconfig.sicong
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public void setSicong(String sicong) {
        this.sicong = sicong == null ? null : sicong.trim();
    }

  
}