package me.daoke.roadrank.dto;

import java.io.Serializable;

public class LoginConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginconfig.id
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginconfig.appKey
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginconfig.base
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    private String base;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginconfig.roadRank
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    private String roadRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginconfig.sicong
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    private String sicong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginconfig.userInfo
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    private String userInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table loginconfig
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginconfig.id
     *
     * @return the value of loginconfig.id
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginconfig.id
     *
     * @param id the value for loginconfig.id
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginconfig.appKey
     *
     * @return the value of loginconfig.appKey
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginconfig.appKey
     *
     * @param appKey the value for loginconfig.appKey
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginconfig.base
     *
     * @return the value of loginconfig.base
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public String getBase() {
        return base;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginconfig.base
     *
     * @param base the value for loginconfig.base
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public void setBase(String base) {
        this.base = base == null ? null : base.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginconfig.roadRank
     *
     * @return the value of loginconfig.roadRank
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public String getRoadRank() {
        return roadRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginconfig.roadRank
     *
     * @param roadRank the value for loginconfig.roadRank
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public void setRoadRank(String roadRank) {
        this.roadRank = roadRank == null ? null : roadRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginconfig.sicong
     *
     * @return the value of loginconfig.sicong
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public String getSicong() {
        return sicong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginconfig.sicong
     *
     * @param sicong the value for loginconfig.sicong
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public void setSicong(String sicong) {
        this.sicong = sicong == null ? null : sicong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginconfig.userInfo
     *
     * @return the value of loginconfig.userInfo
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public String getUserInfo() {
        return userInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginconfig.userInfo
     *
     * @param userInfo the value for loginconfig.userInfo
     *
     * @mbggenerated Sun Apr 24 11:10:05 CST 2016
     */
    public void setUserInfo(String userInfo) {
        this.userInfo = userInfo == null ? null : userInfo.trim();
    }
}