package me.daoke.roadrank.dto;

import java.util.ArrayList;
import java.util.List;

public class UserInfoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public UserInfoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(Long value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(Long value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(Long value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(Long value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(Long value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(Long value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<Long> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<Long> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(Long value1, Long value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(Long value1, Long value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andAccountIDIsNull() {
            addCriterion("accountID is null");
            return (Criteria) this;
        }

        public Criteria andAccountIDIsNotNull() {
            addCriterion("accountID is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIDEqualTo(String value) {
            addCriterion("accountID =", value, "accountID");
            return (Criteria) this;
        }

        public Criteria andAccountIDNotEqualTo(String value) {
            addCriterion("accountID <>", value, "accountID");
            return (Criteria) this;
        }

        public Criteria andAccountIDGreaterThan(String value) {
            addCriterion("accountID >", value, "accountID");
            return (Criteria) this;
        }

        public Criteria andAccountIDGreaterThanOrEqualTo(String value) {
            addCriterion("accountID >=", value, "accountID");
            return (Criteria) this;
        }

        public Criteria andAccountIDLessThan(String value) {
            addCriterion("accountID <", value, "accountID");
            return (Criteria) this;
        }

        public Criteria andAccountIDLessThanOrEqualTo(String value) {
            addCriterion("accountID <=", value, "accountID");
            return (Criteria) this;
        }

        public Criteria andAccountIDLike(String value) {
            addCriterion("accountID like", value, "accountID");
            return (Criteria) this;
        }

        public Criteria andAccountIDNotLike(String value) {
            addCriterion("accountID not like", value, "accountID");
            return (Criteria) this;
        }

        public Criteria andAccountIDIn(List<String> values) {
            addCriterion("accountID in", values, "accountID");
            return (Criteria) this;
        }

        public Criteria andAccountIDNotIn(List<String> values) {
            addCriterion("accountID not in", values, "accountID");
            return (Criteria) this;
        }

        public Criteria andAccountIDBetween(String value1, String value2) {
            addCriterion("accountID between", value1, value2, "accountID");
            return (Criteria) this;
        }

        public Criteria andAccountIDNotBetween(String value1, String value2) {
            addCriterion("accountID not between", value1, value2, "accountID");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordIsNull() {
            addCriterion("daokePassword is null");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordIsNotNull() {
            addCriterion("daokePassword is not null");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordEqualTo(String value) {
            addCriterion("daokePassword =", value, "daokePassword");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordNotEqualTo(String value) {
            addCriterion("daokePassword <>", value, "daokePassword");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordGreaterThan(String value) {
            addCriterion("daokePassword >", value, "daokePassword");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordGreaterThanOrEqualTo(String value) {
            addCriterion("daokePassword >=", value, "daokePassword");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordLessThan(String value) {
            addCriterion("daokePassword <", value, "daokePassword");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordLessThanOrEqualTo(String value) {
            addCriterion("daokePassword <=", value, "daokePassword");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordLike(String value) {
            addCriterion("daokePassword like", value, "daokePassword");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordNotLike(String value) {
            addCriterion("daokePassword not like", value, "daokePassword");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordIn(List<String> values) {
            addCriterion("daokePassword in", values, "daokePassword");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordNotIn(List<String> values) {
            addCriterion("daokePassword not in", values, "daokePassword");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordBetween(String value1, String value2) {
            addCriterion("daokePassword between", value1, value2, "daokePassword");
            return (Criteria) this;
        }

        public Criteria andDaokePasswordNotBetween(String value1, String value2) {
            addCriterion("daokePassword not between", value1, value2, "daokePassword");
            return (Criteria) this;
        }

        public Criteria andWechatIsNull() {
            addCriterion("wechat is null");
            return (Criteria) this;
        }

        public Criteria andWechatIsNotNull() {
            addCriterion("wechat is not null");
            return (Criteria) this;
        }

        public Criteria andWechatEqualTo(String value) {
            addCriterion("wechat =", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatNotEqualTo(String value) {
            addCriterion("wechat <>", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatGreaterThan(String value) {
            addCriterion("wechat >", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatGreaterThanOrEqualTo(String value) {
            addCriterion("wechat >=", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatLessThan(String value) {
            addCriterion("wechat <", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatLessThanOrEqualTo(String value) {
            addCriterion("wechat <=", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatLike(String value) {
            addCriterion("wechat like", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatNotLike(String value) {
            addCriterion("wechat not like", value, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatIn(List<String> values) {
            addCriterion("wechat in", values, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatNotIn(List<String> values) {
            addCriterion("wechat not in", values, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatBetween(String value1, String value2) {
            addCriterion("wechat between", value1, value2, "wechat");
            return (Criteria) this;
        }

        public Criteria andWechatNotBetween(String value1, String value2) {
            addCriterion("wechat not between", value1, value2, "wechat");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(Byte value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(Byte value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(Byte value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Byte value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(Byte value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(Byte value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<Byte> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<Byte> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(Byte value1, Byte value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(Byte value1, Byte value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andBindTypeIsNull() {
            addCriterion("bindType is null");
            return (Criteria) this;
        }

        public Criteria andBindTypeIsNotNull() {
            addCriterion("bindType is not null");
            return (Criteria) this;
        }

        public Criteria andBindTypeEqualTo(Byte value) {
            addCriterion("bindType =", value, "bindType");
            return (Criteria) this;
        }

        public Criteria andBindTypeNotEqualTo(Byte value) {
            addCriterion("bindType <>", value, "bindType");
            return (Criteria) this;
        }

        public Criteria andBindTypeGreaterThan(Byte value) {
            addCriterion("bindType >", value, "bindType");
            return (Criteria) this;
        }

        public Criteria andBindTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("bindType >=", value, "bindType");
            return (Criteria) this;
        }

        public Criteria andBindTypeLessThan(Byte value) {
            addCriterion("bindType <", value, "bindType");
            return (Criteria) this;
        }

        public Criteria andBindTypeLessThanOrEqualTo(Byte value) {
            addCriterion("bindType <=", value, "bindType");
            return (Criteria) this;
        }

        public Criteria andBindTypeIn(List<Byte> values) {
            addCriterion("bindType in", values, "bindType");
            return (Criteria) this;
        }

        public Criteria andBindTypeNotIn(List<Byte> values) {
            addCriterion("bindType not in", values, "bindType");
            return (Criteria) this;
        }

        public Criteria andBindTypeBetween(Byte value1, Byte value2) {
            addCriterion("bindType between", value1, value2, "bindType");
            return (Criteria) this;
        }

        public Criteria andBindTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("bindType not between", value1, value2, "bindType");
            return (Criteria) this;
        }

        public Criteria andHeadNameIsNull() {
            addCriterion("headName is null");
            return (Criteria) this;
        }

        public Criteria andHeadNameIsNotNull() {
            addCriterion("headName is not null");
            return (Criteria) this;
        }

        public Criteria andHeadNameEqualTo(String value) {
            addCriterion("headName =", value, "headName");
            return (Criteria) this;
        }

        public Criteria andHeadNameNotEqualTo(String value) {
            addCriterion("headName <>", value, "headName");
            return (Criteria) this;
        }

        public Criteria andHeadNameGreaterThan(String value) {
            addCriterion("headName >", value, "headName");
            return (Criteria) this;
        }

        public Criteria andHeadNameGreaterThanOrEqualTo(String value) {
            addCriterion("headName >=", value, "headName");
            return (Criteria) this;
        }

        public Criteria andHeadNameLessThan(String value) {
            addCriterion("headName <", value, "headName");
            return (Criteria) this;
        }

        public Criteria andHeadNameLessThanOrEqualTo(String value) {
            addCriterion("headName <=", value, "headName");
            return (Criteria) this;
        }

        public Criteria andHeadNameLike(String value) {
            addCriterion("headName like", value, "headName");
            return (Criteria) this;
        }

        public Criteria andHeadNameNotLike(String value) {
            addCriterion("headName not like", value, "headName");
            return (Criteria) this;
        }

        public Criteria andHeadNameIn(List<String> values) {
            addCriterion("headName in", values, "headName");
            return (Criteria) this;
        }

        public Criteria andHeadNameNotIn(List<String> values) {
            addCriterion("headName not in", values, "headName");
            return (Criteria) this;
        }

        public Criteria andHeadNameBetween(String value1, String value2) {
            addCriterion("headName between", value1, value2, "headName");
            return (Criteria) this;
        }

        public Criteria andHeadNameNotBetween(String value1, String value2) {
            addCriterion("headName not between", value1, value2, "headName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value) {
            addCriterion("updateTime =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value) {
            addCriterion("updateTime <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value) {
            addCriterion("updateTime >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("updateTime >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Integer value) {
            addCriterion("updateTime <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("updateTime <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values) {
            addCriterion("updateTime in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values) {
            addCriterion("updateTime not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
            addCriterion("updateTime between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("updateTime not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(String value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(String value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(String value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(String value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(String value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLike(String value) {
            addCriterion("birthday like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotLike(String value) {
            addCriterion("birthday not like", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<String> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<String> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(String value1, String value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(String value1, String value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andHobbyIsNull() {
            addCriterion("hobby is null");
            return (Criteria) this;
        }

        public Criteria andHobbyIsNotNull() {
            addCriterion("hobby is not null");
            return (Criteria) this;
        }

        public Criteria andHobbyEqualTo(String value) {
            addCriterion("hobby =", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyNotEqualTo(String value) {
            addCriterion("hobby <>", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyGreaterThan(String value) {
            addCriterion("hobby >", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyGreaterThanOrEqualTo(String value) {
            addCriterion("hobby >=", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyLessThan(String value) {
            addCriterion("hobby <", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyLessThanOrEqualTo(String value) {
            addCriterion("hobby <=", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyLike(String value) {
            addCriterion("hobby like", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyNotLike(String value) {
            addCriterion("hobby not like", value, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyIn(List<String> values) {
            addCriterion("hobby in", values, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyNotIn(List<String> values) {
            addCriterion("hobby not in", values, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyBetween(String value1, String value2) {
            addCriterion("hobby between", value1, value2, "hobby");
            return (Criteria) this;
        }

        public Criteria andHobbyNotBetween(String value1, String value2) {
            addCriterion("hobby not between", value1, value2, "hobby");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andActiveCityIsNull() {
            addCriterion("activeCity is null");
            return (Criteria) this;
        }

        public Criteria andActiveCityIsNotNull() {
            addCriterion("activeCity is not null");
            return (Criteria) this;
        }

        public Criteria andActiveCityEqualTo(String value) {
            addCriterion("activeCity =", value, "activeCity");
            return (Criteria) this;
        }

        public Criteria andActiveCityNotEqualTo(String value) {
            addCriterion("activeCity <>", value, "activeCity");
            return (Criteria) this;
        }

        public Criteria andActiveCityGreaterThan(String value) {
            addCriterion("activeCity >", value, "activeCity");
            return (Criteria) this;
        }

        public Criteria andActiveCityGreaterThanOrEqualTo(String value) {
            addCriterion("activeCity >=", value, "activeCity");
            return (Criteria) this;
        }

        public Criteria andActiveCityLessThan(String value) {
            addCriterion("activeCity <", value, "activeCity");
            return (Criteria) this;
        }

        public Criteria andActiveCityLessThanOrEqualTo(String value) {
            addCriterion("activeCity <=", value, "activeCity");
            return (Criteria) this;
        }

        public Criteria andActiveCityLike(String value) {
            addCriterion("activeCity like", value, "activeCity");
            return (Criteria) this;
        }

        public Criteria andActiveCityNotLike(String value) {
            addCriterion("activeCity not like", value, "activeCity");
            return (Criteria) this;
        }

        public Criteria andActiveCityIn(List<String> values) {
            addCriterion("activeCity in", values, "activeCity");
            return (Criteria) this;
        }

        public Criteria andActiveCityNotIn(List<String> values) {
            addCriterion("activeCity not in", values, "activeCity");
            return (Criteria) this;
        }

        public Criteria andActiveCityBetween(String value1, String value2) {
            addCriterion("activeCity between", value1, value2, "activeCity");
            return (Criteria) this;
        }

        public Criteria andActiveCityNotBetween(String value1, String value2) {
            addCriterion("activeCity not between", value1, value2, "activeCity");
            return (Criteria) this;
        }

        public Criteria andCarBrandIsNull() {
            addCriterion("carBrand is null");
            return (Criteria) this;
        }

        public Criteria andCarBrandIsNotNull() {
            addCriterion("carBrand is not null");
            return (Criteria) this;
        }

        public Criteria andCarBrandEqualTo(String value) {
            addCriterion("carBrand =", value, "carBrand");
            return (Criteria) this;
        }

        public Criteria andCarBrandNotEqualTo(String value) {
            addCriterion("carBrand <>", value, "carBrand");
            return (Criteria) this;
        }

        public Criteria andCarBrandGreaterThan(String value) {
            addCriterion("carBrand >", value, "carBrand");
            return (Criteria) this;
        }

        public Criteria andCarBrandGreaterThanOrEqualTo(String value) {
            addCriterion("carBrand >=", value, "carBrand");
            return (Criteria) this;
        }

        public Criteria andCarBrandLessThan(String value) {
            addCriterion("carBrand <", value, "carBrand");
            return (Criteria) this;
        }

        public Criteria andCarBrandLessThanOrEqualTo(String value) {
            addCriterion("carBrand <=", value, "carBrand");
            return (Criteria) this;
        }

        public Criteria andCarBrandLike(String value) {
            addCriterion("carBrand like", value, "carBrand");
            return (Criteria) this;
        }

        public Criteria andCarBrandNotLike(String value) {
            addCriterion("carBrand not like", value, "carBrand");
            return (Criteria) this;
        }

        public Criteria andCarBrandIn(List<String> values) {
            addCriterion("carBrand in", values, "carBrand");
            return (Criteria) this;
        }

        public Criteria andCarBrandNotIn(List<String> values) {
            addCriterion("carBrand not in", values, "carBrand");
            return (Criteria) this;
        }

        public Criteria andCarBrandBetween(String value1, String value2) {
            addCriterion("carBrand between", value1, value2, "carBrand");
            return (Criteria) this;
        }

        public Criteria andCarBrandNotBetween(String value1, String value2) {
            addCriterion("carBrand not between", value1, value2, "carBrand");
            return (Criteria) this;
        }

        public Criteria andCarModelsIsNull() {
            addCriterion("carModels is null");
            return (Criteria) this;
        }

        public Criteria andCarModelsIsNotNull() {
            addCriterion("carModels is not null");
            return (Criteria) this;
        }

        public Criteria andCarModelsEqualTo(String value) {
            addCriterion("carModels =", value, "carModels");
            return (Criteria) this;
        }

        public Criteria andCarModelsNotEqualTo(String value) {
            addCriterion("carModels <>", value, "carModels");
            return (Criteria) this;
        }

        public Criteria andCarModelsGreaterThan(String value) {
            addCriterion("carModels >", value, "carModels");
            return (Criteria) this;
        }

        public Criteria andCarModelsGreaterThanOrEqualTo(String value) {
            addCriterion("carModels >=", value, "carModels");
            return (Criteria) this;
        }

        public Criteria andCarModelsLessThan(String value) {
            addCriterion("carModels <", value, "carModels");
            return (Criteria) this;
        }

        public Criteria andCarModelsLessThanOrEqualTo(String value) {
            addCriterion("carModels <=", value, "carModels");
            return (Criteria) this;
        }

        public Criteria andCarModelsLike(String value) {
            addCriterion("carModels like", value, "carModels");
            return (Criteria) this;
        }

        public Criteria andCarModelsNotLike(String value) {
            addCriterion("carModels not like", value, "carModels");
            return (Criteria) this;
        }

        public Criteria andCarModelsIn(List<String> values) {
            addCriterion("carModels in", values, "carModels");
            return (Criteria) this;
        }

        public Criteria andCarModelsNotIn(List<String> values) {
            addCriterion("carModels not in", values, "carModels");
            return (Criteria) this;
        }

        public Criteria andCarModelsBetween(String value1, String value2) {
            addCriterion("carModels between", value1, value2, "carModels");
            return (Criteria) this;
        }

        public Criteria andCarModelsNotBetween(String value1, String value2) {
            addCriterion("carModels not between", value1, value2, "carModels");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNull() {
            addCriterion("introduction is null");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNotNull() {
            addCriterion("introduction is not null");
            return (Criteria) this;
        }

        public Criteria andIntroductionEqualTo(String value) {
            addCriterion("introduction =", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotEqualTo(String value) {
            addCriterion("introduction <>", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThan(String value) {
            addCriterion("introduction >", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("introduction >=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThan(String value) {
            addCriterion("introduction <", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThanOrEqualTo(String value) {
            addCriterion("introduction <=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLike(String value) {
            addCriterion("introduction like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotLike(String value) {
            addCriterion("introduction not like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionIn(List<String> values) {
            addCriterion("introduction in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotIn(List<String> values) {
            addCriterion("introduction not in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionBetween(String value1, String value2) {
            addCriterion("introduction between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotBetween(String value1, String value2) {
            addCriterion("introduction not between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andIMEIIsNull() {
            addCriterion("IMEI is null");
            return (Criteria) this;
        }

        public Criteria andIMEIIsNotNull() {
            addCriterion("IMEI is not null");
            return (Criteria) this;
        }

        public Criteria andIMEIEqualTo(Long value) {
            addCriterion("IMEI =", value, "IMEI");
            return (Criteria) this;
        }

        public Criteria andIMEINotEqualTo(Long value) {
            addCriterion("IMEI <>", value, "IMEI");
            return (Criteria) this;
        }

        public Criteria andIMEIGreaterThan(Long value) {
            addCriterion("IMEI >", value, "IMEI");
            return (Criteria) this;
        }

        public Criteria andIMEIGreaterThanOrEqualTo(Long value) {
            addCriterion("IMEI >=", value, "IMEI");
            return (Criteria) this;
        }

        public Criteria andIMEILessThan(Long value) {
            addCriterion("IMEI <", value, "IMEI");
            return (Criteria) this;
        }

        public Criteria andIMEILessThanOrEqualTo(Long value) {
            addCriterion("IMEI <=", value, "IMEI");
            return (Criteria) this;
        }

        public Criteria andIMEIIn(List<Long> values) {
            addCriterion("IMEI in", values, "IMEI");
            return (Criteria) this;
        }

        public Criteria andIMEINotIn(List<Long> values) {
            addCriterion("IMEI not in", values, "IMEI");
            return (Criteria) this;
        }

        public Criteria andIMEIBetween(Long value1, Long value2) {
            addCriterion("IMEI between", value1, value2, "IMEI");
            return (Criteria) this;
        }

        public Criteria andIMEINotBetween(Long value1, Long value2) {
            addCriterion("IMEI not between", value1, value2, "IMEI");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andPlateNumberIsNull() {
            addCriterion("plateNumber is null");
            return (Criteria) this;
        }

        public Criteria andPlateNumberIsNotNull() {
            addCriterion("plateNumber is not null");
            return (Criteria) this;
        }

        public Criteria andPlateNumberEqualTo(String value) {
            addCriterion("plateNumber =", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberNotEqualTo(String value) {
            addCriterion("plateNumber <>", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberGreaterThan(String value) {
            addCriterion("plateNumber >", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberGreaterThanOrEqualTo(String value) {
            addCriterion("plateNumber >=", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberLessThan(String value) {
            addCriterion("plateNumber <", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberLessThanOrEqualTo(String value) {
            addCriterion("plateNumber <=", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberLike(String value) {
            addCriterion("plateNumber like", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberNotLike(String value) {
            addCriterion("plateNumber not like", value, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberIn(List<String> values) {
            addCriterion("plateNumber in", values, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberNotIn(List<String> values) {
            addCriterion("plateNumber not in", values, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberBetween(String value1, String value2) {
            addCriterion("plateNumber between", value1, value2, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andPlateNumberNotBetween(String value1, String value2) {
            addCriterion("plateNumber not between", value1, value2, "plateNumber");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNull() {
            addCriterion("idNumber is null");
            return (Criteria) this;
        }

        public Criteria andIdNumberIsNotNull() {
            addCriterion("idNumber is not null");
            return (Criteria) this;
        }

        public Criteria andIdNumberEqualTo(String value) {
            addCriterion("idNumber =", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotEqualTo(String value) {
            addCriterion("idNumber <>", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThan(String value) {
            addCriterion("idNumber >", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberGreaterThanOrEqualTo(String value) {
            addCriterion("idNumber >=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThan(String value) {
            addCriterion("idNumber <", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLessThanOrEqualTo(String value) {
            addCriterion("idNumber <=", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberLike(String value) {
            addCriterion("idNumber like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotLike(String value) {
            addCriterion("idNumber not like", value, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberIn(List<String> values) {
            addCriterion("idNumber in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotIn(List<String> values) {
            addCriterion("idNumber not in", values, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberBetween(String value1, String value2) {
            addCriterion("idNumber between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andIdNumberNotBetween(String value1, String value2) {
            addCriterion("idNumber not between", value1, value2, "idNumber");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNull() {
            addCriterion("userStatus is null");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNotNull() {
            addCriterion("userStatus is not null");
            return (Criteria) this;
        }

        public Criteria andUserStatusEqualTo(Byte value) {
            addCriterion("userStatus =", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotEqualTo(Byte value) {
            addCriterion("userStatus <>", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThan(Byte value) {
            addCriterion("userStatus >", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("userStatus >=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThan(Byte value) {
            addCriterion("userStatus <", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThanOrEqualTo(Byte value) {
            addCriterion("userStatus <=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusIn(List<Byte> values) {
            addCriterion("userStatus in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotIn(List<Byte> values) {
            addCriterion("userStatus not in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusBetween(Byte value1, Byte value2) {
            addCriterion("userStatus between", value1, value2, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("userStatus not between", value1, value2, "userStatus");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeIsNull() {
            addCriterion("idPicbefore is null");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeIsNotNull() {
            addCriterion("idPicbefore is not null");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeEqualTo(String value) {
            addCriterion("idPicbefore =", value, "idPicbefore");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeNotEqualTo(String value) {
            addCriterion("idPicbefore <>", value, "idPicbefore");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeGreaterThan(String value) {
            addCriterion("idPicbefore >", value, "idPicbefore");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeGreaterThanOrEqualTo(String value) {
            addCriterion("idPicbefore >=", value, "idPicbefore");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeLessThan(String value) {
            addCriterion("idPicbefore <", value, "idPicbefore");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeLessThanOrEqualTo(String value) {
            addCriterion("idPicbefore <=", value, "idPicbefore");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeLike(String value) {
            addCriterion("idPicbefore like", value, "idPicbefore");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeNotLike(String value) {
            addCriterion("idPicbefore not like", value, "idPicbefore");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeIn(List<String> values) {
            addCriterion("idPicbefore in", values, "idPicbefore");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeNotIn(List<String> values) {
            addCriterion("idPicbefore not in", values, "idPicbefore");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeBetween(String value1, String value2) {
            addCriterion("idPicbefore between", value1, value2, "idPicbefore");
            return (Criteria) this;
        }

        public Criteria andIdPicbeforeNotBetween(String value1, String value2) {
            addCriterion("idPicbefore not between", value1, value2, "idPicbefore");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindIsNull() {
            addCriterion("idPicbehind is null");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindIsNotNull() {
            addCriterion("idPicbehind is not null");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindEqualTo(String value) {
            addCriterion("idPicbehind =", value, "idPicbehind");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindNotEqualTo(String value) {
            addCriterion("idPicbehind <>", value, "idPicbehind");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindGreaterThan(String value) {
            addCriterion("idPicbehind >", value, "idPicbehind");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindGreaterThanOrEqualTo(String value) {
            addCriterion("idPicbehind >=", value, "idPicbehind");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindLessThan(String value) {
            addCriterion("idPicbehind <", value, "idPicbehind");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindLessThanOrEqualTo(String value) {
            addCriterion("idPicbehind <=", value, "idPicbehind");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindLike(String value) {
            addCriterion("idPicbehind like", value, "idPicbehind");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindNotLike(String value) {
            addCriterion("idPicbehind not like", value, "idPicbehind");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindIn(List<String> values) {
            addCriterion("idPicbehind in", values, "idPicbehind");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindNotIn(List<String> values) {
            addCriterion("idPicbehind not in", values, "idPicbehind");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindBetween(String value1, String value2) {
            addCriterion("idPicbehind between", value1, value2, "idPicbehind");
            return (Criteria) this;
        }

        public Criteria andIdPicbehindNotBetween(String value1, String value2) {
            addCriterion("idPicbehind not between", value1, value2, "idPicbehind");
            return (Criteria) this;
        }

        public Criteria andTrackcountIsNull() {
            addCriterion("trackcount is null");
            return (Criteria) this;
        }

        public Criteria andTrackcountIsNotNull() {
            addCriterion("trackcount is not null");
            return (Criteria) this;
        }

        public Criteria andTrackcountEqualTo(Integer value) {
            addCriterion("trackcount =", value, "trackcount");
            return (Criteria) this;
        }

        public Criteria andTrackcountNotEqualTo(Integer value) {
            addCriterion("trackcount <>", value, "trackcount");
            return (Criteria) this;
        }

        public Criteria andTrackcountGreaterThan(Integer value) {
            addCriterion("trackcount >", value, "trackcount");
            return (Criteria) this;
        }

        public Criteria andTrackcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("trackcount >=", value, "trackcount");
            return (Criteria) this;
        }

        public Criteria andTrackcountLessThan(Integer value) {
            addCriterion("trackcount <", value, "trackcount");
            return (Criteria) this;
        }

        public Criteria andTrackcountLessThanOrEqualTo(Integer value) {
            addCriterion("trackcount <=", value, "trackcount");
            return (Criteria) this;
        }

        public Criteria andTrackcountIn(List<Integer> values) {
            addCriterion("trackcount in", values, "trackcount");
            return (Criteria) this;
        }

        public Criteria andTrackcountNotIn(List<Integer> values) {
            addCriterion("trackcount not in", values, "trackcount");
            return (Criteria) this;
        }

        public Criteria andTrackcountBetween(Integer value1, Integer value2) {
            addCriterion("trackcount between", value1, value2, "trackcount");
            return (Criteria) this;
        }

        public Criteria andTrackcountNotBetween(Integer value1, Integer value2) {
            addCriterion("trackcount not between", value1, value2, "trackcount");
            return (Criteria) this;
        }

        public Criteria andBetrackedcountIsNull() {
            addCriterion("betrackedcount is null");
            return (Criteria) this;
        }

        public Criteria andBetrackedcountIsNotNull() {
            addCriterion("betrackedcount is not null");
            return (Criteria) this;
        }

        public Criteria andBetrackedcountEqualTo(Integer value) {
            addCriterion("betrackedcount =", value, "betrackedcount");
            return (Criteria) this;
        }

        public Criteria andBetrackedcountNotEqualTo(Integer value) {
            addCriterion("betrackedcount <>", value, "betrackedcount");
            return (Criteria) this;
        }

        public Criteria andBetrackedcountGreaterThan(Integer value) {
            addCriterion("betrackedcount >", value, "betrackedcount");
            return (Criteria) this;
        }

        public Criteria andBetrackedcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("betrackedcount >=", value, "betrackedcount");
            return (Criteria) this;
        }

        public Criteria andBetrackedcountLessThan(Integer value) {
            addCriterion("betrackedcount <", value, "betrackedcount");
            return (Criteria) this;
        }

        public Criteria andBetrackedcountLessThanOrEqualTo(Integer value) {
            addCriterion("betrackedcount <=", value, "betrackedcount");
            return (Criteria) this;
        }

        public Criteria andBetrackedcountIn(List<Integer> values) {
            addCriterion("betrackedcount in", values, "betrackedcount");
            return (Criteria) this;
        }

        public Criteria andBetrackedcountNotIn(List<Integer> values) {
            addCriterion("betrackedcount not in", values, "betrackedcount");
            return (Criteria) this;
        }

        public Criteria andBetrackedcountBetween(Integer value1, Integer value2) {
            addCriterion("betrackedcount between", value1, value2, "betrackedcount");
            return (Criteria) this;
        }

        public Criteria andBetrackedcountNotBetween(Integer value1, Integer value2) {
            addCriterion("betrackedcount not between", value1, value2, "betrackedcount");
            return (Criteria) this;
        }

        public Criteria andFriendcountIsNull() {
            addCriterion("friendcount is null");
            return (Criteria) this;
        }

        public Criteria andFriendcountIsNotNull() {
            addCriterion("friendcount is not null");
            return (Criteria) this;
        }

        public Criteria andFriendcountEqualTo(Integer value) {
            addCriterion("friendcount =", value, "friendcount");
            return (Criteria) this;
        }

        public Criteria andFriendcountNotEqualTo(Integer value) {
            addCriterion("friendcount <>", value, "friendcount");
            return (Criteria) this;
        }

        public Criteria andFriendcountGreaterThan(Integer value) {
            addCriterion("friendcount >", value, "friendcount");
            return (Criteria) this;
        }

        public Criteria andFriendcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("friendcount >=", value, "friendcount");
            return (Criteria) this;
        }

        public Criteria andFriendcountLessThan(Integer value) {
            addCriterion("friendcount <", value, "friendcount");
            return (Criteria) this;
        }

        public Criteria andFriendcountLessThanOrEqualTo(Integer value) {
            addCriterion("friendcount <=", value, "friendcount");
            return (Criteria) this;
        }

        public Criteria andFriendcountIn(List<Integer> values) {
            addCriterion("friendcount in", values, "friendcount");
            return (Criteria) this;
        }

        public Criteria andFriendcountNotIn(List<Integer> values) {
            addCriterion("friendcount not in", values, "friendcount");
            return (Criteria) this;
        }

        public Criteria andFriendcountBetween(Integer value1, Integer value2) {
            addCriterion("friendcount between", value1, value2, "friendcount");
            return (Criteria) this;
        }

        public Criteria andFriendcountNotBetween(Integer value1, Integer value2) {
            addCriterion("friendcount not between", value1, value2, "friendcount");
            return (Criteria) this;
        }

        public Criteria andYescountIsNull() {
            addCriterion("yescount is null");
            return (Criteria) this;
        }

        public Criteria andYescountIsNotNull() {
            addCriterion("yescount is not null");
            return (Criteria) this;
        }

        public Criteria andYescountEqualTo(Integer value) {
            addCriterion("yescount =", value, "yescount");
            return (Criteria) this;
        }

        public Criteria andYescountNotEqualTo(Integer value) {
            addCriterion("yescount <>", value, "yescount");
            return (Criteria) this;
        }

        public Criteria andYescountGreaterThan(Integer value) {
            addCriterion("yescount >", value, "yescount");
            return (Criteria) this;
        }

        public Criteria andYescountGreaterThanOrEqualTo(Integer value) {
            addCriterion("yescount >=", value, "yescount");
            return (Criteria) this;
        }

        public Criteria andYescountLessThan(Integer value) {
            addCriterion("yescount <", value, "yescount");
            return (Criteria) this;
        }

        public Criteria andYescountLessThanOrEqualTo(Integer value) {
            addCriterion("yescount <=", value, "yescount");
            return (Criteria) this;
        }

        public Criteria andYescountIn(List<Integer> values) {
            addCriterion("yescount in", values, "yescount");
            return (Criteria) this;
        }

        public Criteria andYescountNotIn(List<Integer> values) {
            addCriterion("yescount not in", values, "yescount");
            return (Criteria) this;
        }

        public Criteria andYescountBetween(Integer value1, Integer value2) {
            addCriterion("yescount between", value1, value2, "yescount");
            return (Criteria) this;
        }

        public Criteria andYescountNotBetween(Integer value1, Integer value2) {
            addCriterion("yescount not between", value1, value2, "yescount");
            return (Criteria) this;
        }

        public Criteria andNocountIsNull() {
            addCriterion("nocount is null");
            return (Criteria) this;
        }

        public Criteria andNocountIsNotNull() {
            addCriterion("nocount is not null");
            return (Criteria) this;
        }

        public Criteria andNocountEqualTo(Integer value) {
            addCriterion("nocount =", value, "nocount");
            return (Criteria) this;
        }

        public Criteria andNocountNotEqualTo(Integer value) {
            addCriterion("nocount <>", value, "nocount");
            return (Criteria) this;
        }

        public Criteria andNocountGreaterThan(Integer value) {
            addCriterion("nocount >", value, "nocount");
            return (Criteria) this;
        }

        public Criteria andNocountGreaterThanOrEqualTo(Integer value) {
            addCriterion("nocount >=", value, "nocount");
            return (Criteria) this;
        }

        public Criteria andNocountLessThan(Integer value) {
            addCriterion("nocount <", value, "nocount");
            return (Criteria) this;
        }

        public Criteria andNocountLessThanOrEqualTo(Integer value) {
            addCriterion("nocount <=", value, "nocount");
            return (Criteria) this;
        }

        public Criteria andNocountIn(List<Integer> values) {
            addCriterion("nocount in", values, "nocount");
            return (Criteria) this;
        }

        public Criteria andNocountNotIn(List<Integer> values) {
            addCriterion("nocount not in", values, "nocount");
            return (Criteria) this;
        }

        public Criteria andNocountBetween(Integer value1, Integer value2) {
            addCriterion("nocount between", value1, value2, "nocount");
            return (Criteria) this;
        }

        public Criteria andNocountNotBetween(Integer value1, Integer value2) {
            addCriterion("nocount not between", value1, value2, "nocount");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontIsNull() {
            addCriterion("idPicfront is null");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontIsNotNull() {
            addCriterion("idPicfront is not null");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontEqualTo(String value) {
            addCriterion("idPicfront =", value, "idPicfront");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontNotEqualTo(String value) {
            addCriterion("idPicfront <>", value, "idPicfront");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontGreaterThan(String value) {
            addCriterion("idPicfront >", value, "idPicfront");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontGreaterThanOrEqualTo(String value) {
            addCriterion("idPicfront >=", value, "idPicfront");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontLessThan(String value) {
            addCriterion("idPicfront <", value, "idPicfront");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontLessThanOrEqualTo(String value) {
            addCriterion("idPicfront <=", value, "idPicfront");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontLike(String value) {
            addCriterion("idPicfront like", value, "idPicfront");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontNotLike(String value) {
            addCriterion("idPicfront not like", value, "idPicfront");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontIn(List<String> values) {
            addCriterion("idPicfront in", values, "idPicfront");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontNotIn(List<String> values) {
            addCriterion("idPicfront not in", values, "idPicfront");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontBetween(String value1, String value2) {
            addCriterion("idPicfront between", value1, value2, "idPicfront");
            return (Criteria) this;
        }

        public Criteria andIdPicfrontNotBetween(String value1, String value2) {
            addCriterion("idPicfront not between", value1, value2, "idPicfront");
            return (Criteria) this;
        }

        public Criteria andCityCodeIsNull() {
            addCriterion("cityCode is null");
            return (Criteria) this;
        }

        public Criteria andCityCodeIsNotNull() {
            addCriterion("cityCode is not null");
            return (Criteria) this;
        }

        public Criteria andCityCodeEqualTo(String value) {
            addCriterion("cityCode =", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotEqualTo(String value) {
            addCriterion("cityCode <>", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeGreaterThan(String value) {
            addCriterion("cityCode >", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("cityCode >=", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeLessThan(String value) {
            addCriterion("cityCode <", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeLessThanOrEqualTo(String value) {
            addCriterion("cityCode <=", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeLike(String value) {
            addCriterion("cityCode like", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotLike(String value) {
            addCriterion("cityCode not like", value, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeIn(List<String> values) {
            addCriterion("cityCode in", values, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotIn(List<String> values) {
            addCriterion("cityCode not in", values, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeBetween(String value1, String value2) {
            addCriterion("cityCode between", value1, value2, "cityCode");
            return (Criteria) this;
        }

        public Criteria andCityCodeNotBetween(String value1, String value2) {
            addCriterion("cityCode not between", value1, value2, "cityCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userInfo
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 21 09:51:27 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}