package me.daoke.roadrank.dto;

import java.io.Serializable;

public class UserInfo extends UserInfoKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.daokePassword
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String daokePassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.wechat
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.gender
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.nickname
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.bindType
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private Byte bindType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.headName
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String headName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.createTime
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.updateTime
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.birthday
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.hobby
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.city
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.activeCity
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String activeCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.carBrand
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String carBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.carModels
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String carModels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.introduction
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.IMEI
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private Long IMEI;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.age
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.plateNumber
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String plateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.name
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.idNumber
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.userStatus
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private Byte userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.idPicbefore
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String idPicbefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.idPicbehind
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String idPicbehind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.trackcount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private Integer trackcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.betrackedcount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private Integer betrackedcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.friendcount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private Integer friendcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.yescount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private Integer yescount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.nocount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private Integer nocount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.idPicfront
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String idPicfront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userInfo.cityCode
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userInfo
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.daokePassword
     *
     * @return the value of userInfo.daokePassword
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getDaokePassword() {
        return daokePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.daokePassword
     *
     * @param daokePassword the value for userInfo.daokePassword
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setDaokePassword(String daokePassword) {
        this.daokePassword = daokePassword == null ? null : daokePassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.wechat
     *
     * @return the value of userInfo.wechat
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.wechat
     *
     * @param wechat the value for userInfo.wechat
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.gender
     *
     * @return the value of userInfo.gender
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.gender
     *
     * @param gender the value for userInfo.gender
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.nickname
     *
     * @return the value of userInfo.nickname
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.nickname
     *
     * @param nickname the value for userInfo.nickname
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.bindType
     *
     * @return the value of userInfo.bindType
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Byte getBindType() {
        return bindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.bindType
     *
     * @param bindType the value for userInfo.bindType
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setBindType(Byte bindType) {
        this.bindType = bindType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.headName
     *
     * @return the value of userInfo.headName
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getHeadName() {
        return headName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.headName
     *
     * @param headName the value for userInfo.headName
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setHeadName(String headName) {
        this.headName = headName == null ? null : headName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.createTime
     *
     * @return the value of userInfo.createTime
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.createTime
     *
     * @param createTime the value for userInfo.createTime
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.updateTime
     *
     * @return the value of userInfo.updateTime
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.updateTime
     *
     * @param updateTime the value for userInfo.updateTime
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.birthday
     *
     * @return the value of userInfo.birthday
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.birthday
     *
     * @param birthday the value for userInfo.birthday
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.hobby
     *
     * @return the value of userInfo.hobby
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.hobby
     *
     * @param hobby the value for userInfo.hobby
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.city
     *
     * @return the value of userInfo.city
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.city
     *
     * @param city the value for userInfo.city
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.activeCity
     *
     * @return the value of userInfo.activeCity
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getActiveCity() {
        return activeCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.activeCity
     *
     * @param activeCity the value for userInfo.activeCity
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setActiveCity(String activeCity) {
        this.activeCity = activeCity == null ? null : activeCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.carBrand
     *
     * @return the value of userInfo.carBrand
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getCarBrand() {
        return carBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.carBrand
     *
     * @param carBrand the value for userInfo.carBrand
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setCarBrand(String carBrand) {
        this.carBrand = carBrand == null ? null : carBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.carModels
     *
     * @return the value of userInfo.carModels
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getCarModels() {
        return carModels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.carModels
     *
     * @param carModels the value for userInfo.carModels
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setCarModels(String carModels) {
        this.carModels = carModels == null ? null : carModels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.introduction
     *
     * @return the value of userInfo.introduction
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.introduction
     *
     * @param introduction the value for userInfo.introduction
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.IMEI
     *
     * @return the value of userInfo.IMEI
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Long getIMEI() {
        return IMEI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.IMEI
     *
     * @param IMEI the value for userInfo.IMEI
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setIMEI(Long IMEI) {
        this.IMEI = IMEI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.age
     *
     * @return the value of userInfo.age
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.age
     *
     * @param age the value for userInfo.age
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.plateNumber
     *
     * @return the value of userInfo.plateNumber
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.plateNumber
     *
     * @param plateNumber the value for userInfo.plateNumber
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber == null ? null : plateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.name
     *
     * @return the value of userInfo.name
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.name
     *
     * @param name the value for userInfo.name
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.idNumber
     *
     * @return the value of userInfo.idNumber
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.idNumber
     *
     * @param idNumber the value for userInfo.idNumber
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.userStatus
     *
     * @return the value of userInfo.userStatus
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.userStatus
     *
     * @param userStatus the value for userInfo.userStatus
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.idPicbefore
     *
     * @return the value of userInfo.idPicbefore
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getIdPicbefore() {
        return idPicbefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.idPicbefore
     *
     * @param idPicbefore the value for userInfo.idPicbefore
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setIdPicbefore(String idPicbefore) {
        this.idPicbefore = idPicbefore == null ? null : idPicbefore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.idPicbehind
     *
     * @return the value of userInfo.idPicbehind
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getIdPicbehind() {
        return idPicbehind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.idPicbehind
     *
     * @param idPicbehind the value for userInfo.idPicbehind
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setIdPicbehind(String idPicbehind) {
        this.idPicbehind = idPicbehind == null ? null : idPicbehind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.trackcount
     *
     * @return the value of userInfo.trackcount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Integer getTrackcount() {
        return trackcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.trackcount
     *
     * @param trackcount the value for userInfo.trackcount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setTrackcount(Integer trackcount) {
        this.trackcount = trackcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.betrackedcount
     *
     * @return the value of userInfo.betrackedcount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Integer getBetrackedcount() {
        return betrackedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.betrackedcount
     *
     * @param betrackedcount the value for userInfo.betrackedcount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setBetrackedcount(Integer betrackedcount) {
        this.betrackedcount = betrackedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.friendcount
     *
     * @return the value of userInfo.friendcount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Integer getFriendcount() {
        return friendcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.friendcount
     *
     * @param friendcount the value for userInfo.friendcount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setFriendcount(Integer friendcount) {
        this.friendcount = friendcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.yescount
     *
     * @return the value of userInfo.yescount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Integer getYescount() {
        return yescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.yescount
     *
     * @param yescount the value for userInfo.yescount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setYescount(Integer yescount) {
        this.yescount = yescount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.nocount
     *
     * @return the value of userInfo.nocount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public Integer getNocount() {
        return nocount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.nocount
     *
     * @param nocount the value for userInfo.nocount
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setNocount(Integer nocount) {
        this.nocount = nocount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.idPicfront
     *
     * @return the value of userInfo.idPicfront
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getIdPicfront() {
        return idPicfront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.idPicfront
     *
     * @param idPicfront the value for userInfo.idPicfront
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setIdPicfront(String idPicfront) {
        this.idPicfront = idPicfront == null ? null : idPicfront.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userInfo.cityCode
     *
     * @return the value of userInfo.cityCode
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userInfo.cityCode
     *
     * @param cityCode the value for userInfo.cityCode
     *
     * @mbggenerated Thu Apr 21 09:51:27 CST 2016
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }
}