package me.daoke.roadrank.dao;

import java.util.List;
import me.daoke.roadrank.dto.UserInfo;
import me.daoke.roadrank.dto.UserInfoCriteria;
import me.daoke.roadrank.dto.UserInfoKey;
import org.apache.ibatis.annotations.Param;

public interface UserInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userInfo
	 * @mbggenerated  Thu Apr 21 09:51:27 CST 2016
	 */
	int countByExample(UserInfoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userInfo
	 * @mbggenerated  Thu Apr 21 09:51:27 CST 2016
	 */
	int deleteByExample(UserInfoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userInfo
	 * @mbggenerated  Thu Apr 21 09:51:27 CST 2016
	 */
	int deleteByPrimaryKey(UserInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userInfo
	 * @mbggenerated  Thu Apr 21 09:51:27 CST 2016
	 */
	int insert(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userInfo
	 * @mbggenerated  Thu Apr 21 09:51:27 CST 2016
	 */
	int insertSelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userInfo
	 * @mbggenerated  Thu Apr 21 09:51:27 CST 2016
	 */
	List<UserInfo> selectByExample(UserInfoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userInfo
	 * @mbggenerated  Thu Apr 21 09:51:27 CST 2016
	 */
	UserInfo selectByPrimaryKey(UserInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userInfo
	 * @mbggenerated  Thu Apr 21 09:51:27 CST 2016
	 */
	int updateByExampleSelective(@Param("record") UserInfo record,
			@Param("example") UserInfoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userInfo
	 * @mbggenerated  Thu Apr 21 09:51:27 CST 2016
	 */
	int updateByExample(@Param("record") UserInfo record,
			@Param("example") UserInfoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userInfo
	 * @mbggenerated  Thu Apr 21 09:51:27 CST 2016
	 */
	int updateByPrimaryKeySelective(UserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table userInfo
	 * @mbggenerated  Thu Apr 21 09:51:27 CST 2016
	 */
	int updateByPrimaryKey(UserInfo record);
}